### PR TITLE
revert commit 17b01430db7 cause Google now use golang.org/x as prefered ...

### PR DESCRIPTION
**Pull request by mikefaille**
...repos

for officials modules

### CODE REVIEW

**Comment by ReAzem** [comment]
Hey, thank you for contributing :)

I switched to ``code.google.com/p/go.crypto`` because ``golang.org/x/crypto`` is not packaged in Debian yet. I produce .debs for gopass so that's kind of a requirement. I wonder what the Debian guys will do. Create a meta package?

**Comment by mikefaille** [comment]
> Hey, thank you for contributing :)
A pleasure :-)

>I switched to code.google.com/p/go.crypto because golang.org/x/crypto is not packaged in Debian yet. I produce .debs for gopass so that's kind of a requirement.
Ah, I use Fedora 21. ;-)

> I wonder what the Debian guys will do. Create a meta package?
:-1:  héhé

For now, I think the cleanest way to resolve this issue is static/incremental .diff for distro specific requiernent and let master as distro agnostic.  
Maybe, you can have depedency injection later.  Preview : https://github.com/facebookgo/inject

**Comment by mikefaille** [comment]
I suggest come back later for Debian X patch as part of build process. By this way, it would be easy to introduce/support Debian X+1, (...)

**Comment by aviau** [comment]
I have just applied it.

**Pull request closed without merging**
